# Training data — manipulative vs normal messages
# Label 1 = manipulative, 0 = normal

messages = [
    ("I never said that, you're making things up", 1),
    ("That never happened, you're imagining things", 1),
    ("You're too sensitive, stop overreacting", 1),
    ("You always twist my words", 1),
    ("I don't know what you're talking about", 1),
    ("You're remembering it wrong", 1),
    ("Stop overthinking everything", 1),
    ("You're being paranoid", 1),

    ("You're the most amazing person I've ever met", 1),
    ("I've never felt this way about anyone before", 1),
    ("You're literally perfect, I don't know what I'd do without you", 1),
    ("You're the only person who truly gets me", 1),
    ("I would do anything for you, you mean everything to me", 1),

    ("After everything I've done for you, this is what I get", 1),
    ("I give you everything and you treat me like this", 1),
    ("You only care when you think you're losing me", 1),
    ("Fine, I'll just suffer alone then", 1),
    ("I guess I'm just not good enough for you", 1),

    ("Your friends are a bad influence on you", 1),
    ("You're different when you're around them", 1),
    ("They don't actually care about you like I do", 1),
    ("Every time you see them you come back acting different", 1),

    ("Maybe we should just break up then", 1),
    ("If you loved me you wouldn't do this", 1),
    ("Prove you care about us, skip tonight", 1),
    ("Don't expect me to be okay with this", 1),

    ("So I'm the villain now? typical", 1),
    ("You always make me the bad guy", 1),
    ("I can't believe you're attacking me like this", 1),
    ("Wow okay so everything is always my fault", 1),

    ("you made me do this", 1),
    ("nobody else would put up with you", 1),
    ("you're lucky I'm still here", 1),
    ("I do everything for you and you do nothing", 1),
    ("you're so ungrateful", 1),
    ("stop being so dramatic", 1),
    ("you're overreacting as usual", 1),
    ("I was just joking you're so sensitive", 1),
    ("you never appreciate anything I do", 1),
    ("this is exactly why people don't like you", 1),

    ("hey how are you doing today", 0),
    ("sounds good, see you at 7", 0),
    ("I'm running a bit late, be there in 10", 0),
    ("did you eat lunch yet", 0),
    ("good morning, hope you slept well", 0),
    ("that movie was really good", 0),
    ("I'm proud of you for doing that", 0),
    ("let me know if you need anything", 0),
    ("I understand, take your time", 0),
    ("that makes sense, thanks for explaining", 0),
    ("I hear you, that sounds really hard", 0),
    ("you did great today", 0),
    ("I'm sorry that happened to you", 0),
    ("what do you want to do this weekend", 0),
    ("I disagree but I get where you're coming from", 0),
    ("can we talk about this later when we're both calm", 0),
    ("I was wrong about that, I'm sorry", 0),
    ("your feelings are valid", 0),
    ("I'll support whatever you decide", 0),
    ("that's completely fair", 0),
    ("want to grab coffee tomorrow", 0),
    ("I think we should talk about this calmly", 0),
    ("that's a good point actually", 0),
    ("I missed you today", 0),
    ("how was your day", 0),
    ("I'm happy for you", 0),
    ("let's figure this out together", 0),
    ("I respect your decision", 0),
    ("thanks for being honest with me", 0),
    ("I was thinking about what you said", 0),
]