# Training data — manipulative vs normal messages
# Label 1 = manipulative, 0 = normal

messages = [
    ("I never said that, you're making things up", 1),
    ("That never happened, you're imagining things", 1),
    ("You're too sensitive, stop overreacting", 1),
    ("You always twist my words", 1),
    ("I don't know what you're talking about", 1),
    ("You're remembering it wrong", 1),
    ("Stop overthinking everything", 1),
    ("You're being paranoid", 1),
    ("You're the most amazing person I've ever met", 1),
    ("I've never felt this way about anyone before", 1),
    ("You're literally perfect, I don't know what I'd do without you", 1),
    ("You're the only person who truly gets me", 1),
    ("I would do anything for you, you mean everything to me", 1),
    ("After everything I've done for you, this is what I get", 1),
    ("I give you everything and you treat me like this", 1),
    ("You only care when you think you're losing me", 1),
    ("Fine, I'll just suffer alone then", 1),
    ("I guess I'm just not good enough for you", 1),
    ("Your friends are a bad influence on you", 1),
    ("You're different when you're around them", 1),
    ("They don't actually care about you like I do", 1),
    ("Every time you see them you come back acting different", 1),
    ("Maybe we should just break up then", 1),
    ("If you loved me you wouldn't do this", 1),
    ("Prove you care about us, skip tonight", 1),
    ("Don't expect me to be okay with this", 1),
    ("So I'm the villain now? typical", 1),
    ("You always make me the bad guy", 1),
    ("I can't believe you're attacking me like this", 1),
    ("Wow okay so everything is always my fault", 1),
    ("you made me do this", 1),
    ("nobody else would put up with you", 1),
    ("you're lucky I'm still here", 1),
    ("I do everything for you and you do nothing", 1),
    ("you're so ungrateful", 1),
    ("stop being so dramatic", 1),
    ("you're overreacting as usual", 1),
    ("I was just joking you're so sensitive", 1),
    ("you never appreciate anything I do", 1),
    ("this is exactly why people don't like you", 1),
    ("hey how are you doing today", 0),
    ("sounds good, see you at 7", 0),
    ("I'm running a bit late, be there in 10", 0),
    ("did you eat lunch yet", 0),
    ("good morning, hope you slept well", 0),
    ("that movie was really good", 0),
    ("I'm proud of you for doing that", 0),
    ("let me know if you need anything", 0),
    ("I understand, take your time", 0),
    ("that makes sense, thanks for explaining", 0),
    ("I hear you, that sounds really hard", 0),
    ("you did great today", 0),
    ("I'm sorry that happened to you", 0),
    ("what do you want to do this weekend", 0),
    ("I disagree but I get where you're coming from", 0),
    ("can we talk about this later when we're both calm", 0),
    ("I was wrong about that, I'm sorry", 0),
    ("your feelings are valid", 0),
    ("I'll support whatever you decide", 0),
    ("that's completely fair", 0),
    ("want to grab coffee tomorrow", 0),
    ("I think we should talk about this calmly", 0),
    ("that's a good point actually", 0),
    ("I missed you today", 0),
    ("how was your day", 0),
    ("I'm happy for you", 0),
    ("let's figure this out together", 0),
    ("I respect your decision", 0),
    ("thanks for being honest with me", 0),
    ("I was thinking about what you said", 0),
    ("tu pagal hai kya, maine kabhi aisa nahi kaha", 1),
    ("teri wajah se sab kharab ho gaya", 1),
    ("tu itni sensitive kyun hai har cheez pe", 1),
    ("main ne kab bola aisa, tu toh bas drama karti hai", 1),
    ("tujhe kuch nahi pata, bas meri baat sun", 1),
    ("agar tu mujhse pyaar karti toh aisa nahi karti", 1),
    ("tu hi toh problem hai humare beech mein", 1),
    ("mere saath itna bura koi nahi karta jitna tu karti hai", 1),
    ("aaj kya khana hai ghar pe", 0),
    ("kal milte hain coffee pe", 0),
    ("movie kaisi lagi tujhe", 0),
    ("sab theek hai na tere saath", 0),
    ("teri help chahiye thi ek kaam mein", 0),
    ("bahut achha kiya tune yaar", 0),
    ("I'll be there in 10 minutes.", 0),
("Can we pick this up tomorrow morning?", 0),
("I don't think that's a good idea.", 0),
("Thanks for letting me know.", 0),
("I'm sorry, I forgot to call you back.", 0),
("Let's figure this out together.", 0),
("I completely understand why you're upset.", 0),
("Are you free for a quick chat later?", 0),
("That sounds like a great plan.", 0),
("I need some time to process this.", 0),
("I respect your decision.", 0),
("Have a great day at work!", 0),
("Could you please pass me the remote?", 0),
("I disagree with you on that point.", 0),
("Let me know if you need any help.", 0),
("I'm really proud of what you achieved.", 0),
("It's okay to feel sad about this.", 0),
("Don't worry about it, it happens.", 0),
("I'll order the pizza, you pick the movie.", 0),
("Just checking in to see how you are.", 0),
("I think we should take a break.", 0),
("You did a fantastic job today.", 0),
("I'm not comfortable with that.", 0),
("Can you explain what you mean?", 0),
("I'm heading to the grocery store, need anything?", 0),
("I'm sorry for raising my voice earlier.", 0),
("Let's agree to disagree.", 0),
("What do you want for dinner?", 0),
("I appreciate your honesty.", 0),
("I'm feeling a little stressed today.", 0),
("Take all the time you need.", 0),
("That's a valid point, I hadn't thought of that.", 0),
("Please let me know your thoughts.", 0),
("I'm sorry you're going through a tough time.", 0),
("Let's reschedule for next week.", 0),
("I value our friendship a lot.", 0),
("I'll text you when I leave.", 0),
("Can we talk about how that made me feel?", 0),
("Good morning! Hope you slept well.", 0),
("I really liked your presentation.", 0),
("Let's just relax tonight.", 0),
("I'm not sure I understand, can you clarify?", 0),
("Thanks for listening to me.", 0),
("I owe you an apology for yesterday.", 0),
("Do you want some space right now?", 0),
("I'm here for you if you want to talk.", 0),
("Let's focus on finding a solution.", 0),
("I had a great time hanging out.", 0),
("Please be safe on the drive back.", 0),
("I'll support whatever you decide to do.", 0),
("You're too sensitive, learn to take a joke.", 1),
("I wouldn't have to yell if you just listened to me.", 1),
("You're the only reason I'm depressed.", 1),
("No one else will ever love you like I do.", 1),
("I never said that, your memory is terrible.", 1),
("You always ruin everything.", 1),
("If you leave me, I don't know what I'll do to myself.", 1),
("You're crazy if you think that's what happened.", 1),
("After everything I've done for you, this is how you repay me?", 1),
("You're imagining things again.", 1),
("I'm sorry you're offended, but I was just being honest.", 1),
("You make me act this way.", 1),
("Your friends are trying to turn you against me.", 1),
("Why do you always have to start drama?", 1),
("You're so ungrateful.", 1),
("I guess I'm just the worst person in the world then.", 1),
("You're acting exactly like your mother.", 1),
("If you cared about me, you wouldn't hang out with them.", 1),
("You don't know what you're talking about.", 1),
("I only did it because I love you.", 1),
("You're overreacting as usual.", 1),
("You always make everything about you.", 1),
("Stop playing the victim.", 1),
("You're completely irrational right now.", 1),
("I didn't hit you that hard, stop crying.", 1),
("You should be thanking me instead of complaining.", 1),
("You can't do anything right, can you?", 1),
("I'm the only one who actually cares about you.", 1),
("You're lucky I'm even with you.", 1),
("If you go out tonight, don't bother coming back.", 1),
("You deliberately try to make me angry.", 1),
("Why can't you be more like my ex?", 1),
("You're just trying to manipulate me.", 1),
("I don't know why you're making such a big deal out of this.", 1),
("You're the one who needs therapy, not me.", 1),
("You'll never find anyone better than me.", 1),
("You're deliberately twisting my words.", 1),
("I was just trying to help, but you're so defensive.", 1),
("You're always finding things to complain about.", 1),
("You literally have no idea how the real world works.", 1),
("I can't believe you're bringing this up again.", 1),
("You made me lose my temper.", 1),
("You don't really love me, do you?", 1),
("You're pathetic when you cry.", 1),
("You're just jealous of my success.", 1),
("You wouldn't understand, it's too complicated for you.", 1),
("Stop being so dramatic.", 1),
("You owe me for what I did yesterday.", 1),
("You're remembering it entirely wrong.", 1),
("I guess my feelings just don't matter to you.", 1),
("Tumne khana kha liya kya?", 0),
("Mujhe thoda time chahiye sochne ke liye.", 0),
("Kal subah call karta hu, abhi thoda busy hu.", 0),
("Sorry, galti meri thi, mujhe dhyan rakhna chahiye tha.", 0),
("Hum is baare mein aaram se baith ke baat karenge.", 0),
("Tumhara idea kafi sahi lag raha hai.", 0),
("Main samajh raha hu tum kaisa feel kar rahe ho.", 0),
("Aaj mood nahi hai bahar jane ka, ghar pe hi rehte hain.", 0),
("Tumhe madad chahiye to bata dena.", 0),
("All the best tumhare exam ke liye!", 0),
("Mujhe lagta hai hum dono ke views alag hain is topic pe.", 0),
("Chalo koi nahi, agli baar dekh lenge.", 0),
("Mera wo intention bilkul nahi tha.", 0),
("Tum aaram karo, main sambhal lunga baki kaam.", 0),
("Mujhe tumhara kaam bohot pasand aaya.", 0),
("Safe travel, pahunch ke text karna.", 0),
("Kya hum weekend par mil sakte hain?", 0),
("Ye dress tum par bohot achi lag rahi hai.", 0),
("Mujhe is baare mein thodi aur information chahiye.", 0),
("Tumhari awaaz sun kar acha laga.", 0),
("Main abhi nikal raha hu office se.", 0),
("Koi baat nahi yaar, chalta hai itna toh.", 0),
("Tum theek toh ho na? Chehra utra hua lag raha hai.", 0),
("Main tumhari problem samajhne ki koshish kar raha hu.", 0),
("Aao chai peete hain.", 0),
("Mujhe batao kahan aana hai.", 0),
("Main sach mein bahut thak gaya hu aaj.", 0),
("Tumhara stand bilkul sahi tha us meeting mein.", 0),
("Sorry main phone nahi utha paya, drive kar raha tha.", 0),
("Hum baad mein discuss kar lenge isko.", 0),
("Tum apne time ke hisaab se bata dena.", 0),
("Mujhe lagta hai thodi misunderstanding ho gayi thi.", 0),
("Tumne bahut mehnat ki hai is project par.", 0),
("Chalo movie dekhne chalte hain.", 0),
("Main nahi aa paunga, mera kuch aur plan hai.", 0),
("Take care of your health.", 0),
("Tumhara naya phone kaisa chal raha hai?", 0),
("Haan, main is baat se sehmat hu.", 0),
("Thoda aur sochte hain is baare mein.", 0),
("Sorry yaar, aage se dhyan rakhunga.", 0),
("Please lights off kar dena sote time.", 0),
("Kaisa raha tumhara din?", 0),
("Mujhe lagta hai hume ek break lena chahiye.", 0),
("Main support karunga chahe tum koi bhi decision lo.", 0),
("Pahunch ke location bhej dena.", 0),
("Main kal tak bhej dunga file.", 0),
("Tum apna khayal rakhna.", 0),
("Hum saath milkar solution nikal lenge.", 0),
("Khaane mein kya mangaun?", 0),
("Mujhe uspe pura bharosa hai.", 0),
("Tum hamesha choti si baat ka issue bana dete ho.", 1),
("Tumhare doston ne hi tumhara dimaag kharab kiya hai.", 1),
("Agar tum sach mein mujhse pyaar karte to aisa nahi bolte.", 1),
("Meri toh koi aukaat hi nahi hai na tumhari nazar mein.", 1),
("Tumhara dimaag kharab ho gaya hai, maine aisa kuch nahi kaha.", 1),
("Sab meri hi galti hai na, hamesha mujhe hi galat thehrao.", 1),
("Tumhe jhelna kisi aur ke bas ki baat nahi hai.", 1),
("Maine jo bhi kiya sirf tumhari bhalai ke liye kiya tha.", 1),
("Tum kabhi kisi ka ehsaan nahi mante.", 1),
("Tumhe yaad hi nahi rehta, tumne hi bola tha pehle.", 1),
("Tum rote rahoge toh main baat nahi karunga.", 1),
("Tumhara problem ye hai ki tum sunte nahi ho kabhi.", 1),
("Main marr jaunga toh tumhe pata chalega.", 1),
("Tum deliberately mujhe gussa dilate ho.", 1),
("Mujhe laga tha tum alag ho, par tum bhi baakiyon jaise nikle.", 1),
("Tumhe bas bahana chahiye mujhse ladne ka.", 1),
("Tumhe kya lagta hai duniya tumhare hisaab se chalegi?", 1),
("Tum itne sensitive kyun ban rahe ho aaj kal?", 1),
("Tumhe lagta hai tum hamesha sahi hote ho.", 1),
("Apne parents se jaakar pucho unhone tumhe kya sikhaya hai.", 1),
("Agar tum wahan gaye toh mujhse rishta khatam.", 1),
("Mujhe majboor mat karo waisa behave karne pe.", 1),
("Tum bina mere kuch nahi kar sakte life mein.", 1),
("Main hi pagal tha jo maine tumhari madad ki.", 1),
("Tumhare drame kabhi khatam nahi hote.", 1),
("Meri feeling ki toh kisi ko parwah hi nahi hai.", 1),
("Tum pagal ho rahe ho, aisi baat toh hui hi nahi.", 1),
("Tum mujhe control karne ki koshish kar rahe ho.", 1),
("Ye sab faltu ka overthinking band karo.", 1),
("Main akela pad gaya hu tumhari wajah se.", 1),
("Tumne meri reputation kharab kar di sabke samne.", 1),
("Tumko samajhna namumkin hai.", 1),
("Baar baar ek hi topic kyun laate ho beech mein?", 1),
("Tumko lagta hai tumhare alawa kisi ki life mein problem nahi hai?", 1),
("Tum jaan-boojh kar mujhe hurt karte ho.", 1),
("Main tumse behtar deserve karta hu.", 1),
("Tumhare dimag mein negative cheezein hi ghumti hain.", 1),
("Dekha, tumhare dost kaise hain, isiliye main door rehta hu unse.", 1),
("Agar main chala gaya, toh rona mat aakar.", 1),
("Tum apne faayde ke liye mera use kar rahe ho.", 1),
("Mujhe mafi mangne ki zaroorat nahi hai, galti tumhari thi.", 1),
("Tum hamesha victim card play karte ho.", 1),
("Main badal gaya kyunki tumne mujhe majboor kiya.", 1),
("Tumhari soch hi itni choti hai.", 1),
("Har cheez ko personal lena zaroori hai kya?", 1),
("Tumhe kisi ki parwah nahi, bas apne aap se matlab hai.", 1),
("Maine tumhare liye apni puri life sacrifice kar di.", 1),
("Tum khud ko samajhte kya ho?", 1),
("Agar mere saath rahna hai toh meri baat sunni padegi.", 1),
("Tum hallucinate kar rahe ho, maine aisi koi promise nahi ki thi.", 1),
("Call me when you're free.", 0),
("I love spending time with you.", 0),
("Tum phir se natak kar rahe ho.", 1),
("You always imagine the worst things about me.", 1),
("Mujhe lagta hai tumhe rest karna chahiye.", 0),
("I'll call you as soon as my meeting ends.", 0),
("Please let me know when you reach safely.", 0),
("I'm not really feeling up to going out tonight.", 0),
("Can you help me understand what went wrong?", 0),
("I totally get why that made you feel bad.", 0),
("Let's try a different approach next time.", 0),
("I'm sorry for being late, traffic was terrible.", 0),
("Are we still on for our lunch plan?", 0),
("I appreciate you taking the time to listen to me.", 0),
("I think we need to set some boundaries here.", 0),
("You always blow everything out of proportion.", 1),
("I wouldn't have lied if you weren't so judgmental.", 1),
("You owe me an apology for making me angry.", 1),
("No one else is ever going to put up with your attitude.", 1),
("You're just trying to make me look bad in front of them.", 1),
("If you really loved me, you'd cancel your plans.", 1),
("You never listen, that's why you're always confused.", 1),
("I never promised you anything, you're delusional.", 1),
("Why do you always have to play the victim?", 1),
("You made me act this way, it's your fault.", 1),
("Main ghar pahunch kar text karta hu.", 0),
("Tumne aaj lunch mein kya khaya?", 0),
("Aaj office mein bahut zyada kaam tha.", 0),
("Weekend pe tumhara kya plan ban raha hai?", 0),
("Mujhe tumhara point of view samajh aa raha hai.", 0),
("Sorry yaar, main call karna bhool gaya tha.", 0),
("Agar koi help chahiye ho toh bina soche bata dena.", 0),
("Main thoda late ho jaunga aaj, please start kar dena.", 0),
("Mujhe lagta hai hume thodi baat karni chahiye is baare mein.", 0),
("Tum apna dhyan rakhna waha par.", 0),
("Tumhe toh hamesha rona hi aata hai.", 1),
("Maine apni puri life tumhare liye barbaad kar di.", 1),
("Tumhare dost tumhe mere khilaf bhadka rahe hain.", 1),
("Meri toh koi value hi nahi hai tumhari life mein, haina?", 1),
("Tum pagal ho gaye ho, maine aisa kab bola?", 1),
("Agar tum waha gaye toh mera mara muh dekhoge.", 1),
("Tum hamesha apni hi chalate ho.", 1),
("Tum bas mujhe control karna chahte ho, aur kuch nahi.", 1),
("Dekh liya tumhara asli chehra aaj.", 1),
("Tum kabhi kisi ke sage nahi ho sakte.", 1),
("I'll be offline for the next few hours to focus on this.", 0),
("Can you send me that document when you're free?", 0),
("I think we should rethink this entire strategy.", 0),
("Thanks for the heads up, I'll check it out.", 0),
("I'm feeling a bit overwhelmed with work today.", 0),
("Let's try to wrap this up by 5 PM.", 0),
("I'm so happy for your promotion!", 0),
("That sounds really frustrating to deal with.", 0),
("Are you okay with this plan, or should we change it?", 0),
("I need some alone time this evening.", 0),
("You're just too insecure, that's your problem.", 1),
("I only yell because you force me to.", 1),
("If you walk out that door, we are done forever.", 1),
("You should be grateful I'm even talking to you after what you did.", 1),
("You literally have no friends because of your personality.", 1),
("I guess I'll just do everything myself since you're useless.", 1),
("You're deliberately trying to ruin my evening.", 1),
("Why can't you just let things go?", 1),
("You don't remember it right because you were barely paying attention.", 1),
("You're the reason I drink.", 1),
("Meeting kab start hogi bata dena.", 0),
("Chalo ek coffee break lete hain.", 0),
("Mujhe is baare mein thoda padhna padega pehle.", 0),
("Tumhara naya project kaisa chal raha hai?", 0),
("Main samajh sakta hu ki tum kyu pareshan ho.", 0),
("Mujhe tumhara decision manzoor hai.", 0),
("Mujhse galti ho gayi, uske liye mafi chahta hu.", 0),
("Kya main tumhe kal subah call kar sakta hu?", 0),
("Mujhe kal chutti chahiye thi, tabiyat theek nahi hai.", 0),
("Hum isko next week discuss kar lenge.", 0),
("Tumhe meri feelings ki kabhi parvah nahi thi.", 1),
("Agar pyaar karte toh mere message ka wait nahi karte.", 1),
("Maine toh bas mazak kiya tha, tum bore ho ekdum.", 1),
("Tum jaan-boojhkar mujhe ignore kar rahe ho.", 1),
("Tumhare parents ko toh koi tameez hi nahi hai.", 1),
("Aisa kuch nahi hua tha, tum sapne dekh rahe ho.", 1),
("Mujhe pata tha tum dhokha doge.", 1),
("Main sirf tumhara bhala chahta hu isiliye daant raha hu.", 1),
("Tumhare rone se kuch nahi hone wala ab.", 1),
("Sab meri galti hai, main hi bura hu, khush ab?", 1),
("Have a safe flight!", 0),
("I'll transfer the money by this evening.", 0),
("Let's go for a walk, the weather is nice.", 0),
("I don't agree, but I hear what you're saying.", 0),
("Can you pick up some milk on your way back?", 0),
("I really enjoyed our conversation today.", 0),
("I'm proud of the progress you've made.", 0),
("Let's not argue about this over text.", 0),
("I need to focus on my exams right now.", 0),
("Thank you for helping me out yesterday.", 0),
("You always twist my words to make me the bad guy.", 1),
("Nobody will ever tolerate you the way I do.", 1),
("You're making a big deal out of literally nothing.", 1),
("I guess my needs just don't matter at all.", 1),
("If you don't do this for me, you don't care about our relationship.", 1),
("You're remembering things wrong, like you always do.", 1),
("You're just jealous and it's pathetic.", 1),
("I don't know why I even bother trying with you.", 1),
("You provoked me into saying those things.", 1),
("Your friends are toxic and you need to cut them off.", 1),
("Main kal tak tumhe update deta hu.", 0),
("Aaj dinner mein pizza order kar lein?", 0),
("Tumhare support ke liye bahut shukriya.", 0),
("Mujhe lagta hai hume is baare mein kisi aur se poochna chahiye.", 0),
("Tum sach mein bahut acha gaate ho.", 0),
("Main tumhari situation ko deeply samajhne ki koshish kar raha hu.", 0),
("Mujhe gussa aa raha tha isliye main chup ho gaya.", 0),
("Ghar aakar aaram kar lena tum.", 0),
("Main tumhe thodi der mein file bhejta hu.", 0),
("All the best tumhare naye job ke liye!", 0),
("Tum ek number ke swarthi insaan ho.", 1),
("Main apna sab kuch chhod ke tumhare paas aaya, aur tumne kya diya?", 1),
("Tumhe lagta hai tum bahut smart ho, par tum ho nahi.", 1),
("Main janta hu tum mujhe chhodne ka plan bana rahe ho.", 1),
("Meri tabiyat tumhari inhi harkaton ki wajah se kharab rahti hai.", 1),
("Tumhe khud pe sharam aani chahiye.", 1),
("Tum bas attention chahte ho isliye aisi batein kar rahe ho.", 1),
("Mujhe sikhaane ki koshish mat karo tum.", 1),
("Tum kabhi kisi se sachha pyaar nahi kar sakte.", 1),
("Maine bola na maine aisa nahi kiya, baat khatam.", 1),
("I'm feeling really anxious about this presentation.", 0),
("Let's take a break and grab some lunch.", 0),
("I completely stand by my decision.", 0),
("I'm sorry if my words hurt your feelings.", 0),
("Could you give me some feedback on this draft?", 0),
("I don't have enough bandwidth for a new project right now.", 0),
("Happy birthday! Hope you have a wonderful year ahead.", 0),
("I'm here to listen whenever you're ready to talk.", 0),
("Let's compromise and meet halfway.", 0),
("I'm just really tired, it has nothing to do with you.", 0),
("Fine, do whatever you want. Don't come crying to me later.", 1),
("You're the one who needs to change, not me.", 1),
("I sacrifice everything for you and you give me nothing in return.", 1),
("You wouldn't be crying if you actually felt sorry.", 1),
("You're just trying to start an argument.", 1),
("Stop being so hysterical.", 1),
("I only kept it from you to protect you.", 1),
("You're lucky I haven't left you yet.", 1),
("You always have to ruin my good mood, don't you?", 1),
("Your family is the reason we have problems.", 1),
("Laptop charge par laga dena please.", 0),
("Maine flight tickets book kar di hain.", 0),
("Tum sahi keh rahe ho, maine galat socha tha.", 0),
("Mujhe tumhara dress sense bahut acha lagta hai.", 0),
("Main soch raha tha hum weekend pe trip pe chalein.", 0),
("Tumhe koi baat buri lagi ho toh bata dena.", 0),
("Mujhe thodi akele rehne ki zarurat hai.", 0),
("Baad mein baat karte hain is baare mein aaram se.", 0),
("Main apna best dene ki koshish karunga.", 0),
("Thanks yaar, tumne din bana diya.", 0),
("Tum har baat pe jhagda kyu shuru kar dete ho?", 1),
("Tumhe kisi ki feeling ki qadar nahi hai.", 1),
("Main hi pagal tha jo maine tumpe trust kiya.", 1),
("Tum hallucinate kar rahe ho, aisi koi baat nahi hui.", 1),
("Agar meri baat nahi manni toh nikal jao yaha se.", 1),
("Tum apne aap ko kuch zyada hi samajhte ho.", 1),
("Tumhari wajah se meri life narak ban gayi hai.", 1),
("Maine toh aisi koi promise nahi ki, tumne hi soch liya hoga.", 1),
("Tum bas apne baare mein sochte ho.", 1),
("Tumhara rona dhona fir shuru ho gaya.", 1),
("Can we discuss this when you're calmer?", 0),
("I really value your input on this project.", 0),
("I'll have to check my calendar and get back to you.", 0),
("I'm sorry, I misunderstood what you meant.", 0),
("That's a very fair point.", 0),
("Let's postpone the meeting to tomorrow.", 0),
("I hope you're feeling better today.", 0),
("I'll take care of the kids tonight, you relax.", 0),
("Please don't hesitate to ask if you need anything.", 0),
("I'm leaving the office now.", 0),
("You're acting crazy right now, calm down.", 1),
("I'm the victim here, not you.", 1),
("You always pick fights when I'm already stressed.", 1),
("Why are you so obsessed with the past?", 1),
("You wouldn't understand, you're not smart enough.", 1),
("I only insulted you because you provoked me.", 1),
("If you tell anyone about this, I'll deny it.", 1),
("You're so needy, it's suffocating.", 1),
("You know exactly what you did to make me mad.", 1),
("Nobody really likes you, they just pretend to.", 1),
("Mera kal ka plan cancel ho gaya hai.", 0),
("Tumhe time mile toh mujhe ring karna.", 0),
("Main tumhari mehnat ki qadar karta hu.", 0),
("Tum is baare mein kya sochte ho?", 0),
("Mujhe tumse mil kar kafi acha laga.", 0),
("Mujhe samajh nahi aa raha hai, explain karoge?", 0),
("Main theek hu, bas thodi neend poori karni hai.", 0),
("Mujhe kal subah jaldi uthna hai.", 0),
("Main kal tumhari taraf aaunga kaam se.", 0),
("Chinta mat karo, sab theek ho jayega.", 0),
("Tumhe toh sach batana hi bekaar hai.", 1),
("Tumhara dimaag hamesha ulti disha mein hi chalta hai.", 1),
("Meri aukaat hi kya hai tumhare doston ke saamne.", 1),
("Main tumhe chhod ke chala jaunga toh tum ro doge.", 1),
("Maine kab kaha aisa? Tum jhooth bol rahe ho.", 1),
("Tumhare saath rehne se acha toh main akela rahu.", 1),
("Tumhe lagta hai duniya tumhare ishaare par nachegi.", 1),
("Agar thodi akal hoti toh tum aisi harkat nahi karte.", 1),
("Main apni galti isliye nahi maanunga kyuki meri koi galti nahi hai.", 1),
("Tumhe jhelna asaan nahi hai.", 1),
("Please water the plants before you leave.", 0),
("I'm not comfortable sharing that information.", 0),
("Let me double-check and get back to you.", 0),
("I think we did a great job today.", 0),
("I'm feeling a bit under the weather.", 0),
("I'd love to hear more about your trip.", 0),
("That's completely fine by me.", 0),
("I'm just grabbing a coffee, want one?", 0),
("I really appreciate your patience.", 0),
("Let's catch up over the weekend.", 0),
("You always try to control every little thing I do.", 1),
("I guess I'm just a horrible partner then.", 1),
("If you loved me, you would just say yes.", 1),
("You're making yourself look ridiculous right now.", 1),
("You remember everything wrong.", 1),
("I was just joking, don't be so sensitive.", 1),
("You should be begging for my forgiveness.", 1),
("I'm doing you a favor by staying with you.", 1),
("You always have to be the center of attention.", 1),
("You're just paranoid.", 1),
("Wifi ka password kya hai?", 0),
("Tum kab tak wapas aaoge?", 0),
("Main agree nahi karta, par let it be.", 0),
("Mujhe tumhari ye aadat bahut pasand hai.", 0),
("Aaj mausam bahut acha ho raha hai.", 0),
("Tumse baat karke mind relax ho gaya.", 0),
("Please call me jab free ho.", 0),
("Main tumhari help karunga is project mein.", 0),
("Drive safe, aur seatbelt pehen lena.", 0),
("Sorry, main tumhe update dena bhool gaya.", 0),
("Tumne mera jeena haram kar rakha hai.", 1),
("Tumhare maa baap ne yahi sikhaya hai tumhe?", 1),
("Mujhe gussa aata hai toh tumhe chup rehna chahiye.", 1),
("Tumhara rona ek weapon hai mujhe chup karane ka.", 1),
("Main hi bewaqoof hu jo tumhari care karta hu.", 1),
("Tum intentionally mujhe embarrass karte ho logon ke saamne.", 1),
("Tumhari wajah se mere saare dost chhut gaye.", 1),
("Agar main gussa karta hu, toh wajah tum hi hote ho.", 1),
("Main tumse better deserve karta hu.", 1),
("Tumhe na bolne ki aadat daal leni chahiye ab.", 1),
("I'm going to log off for the night.", 0),
("Do you need any help with the groceries?", 0),
("I don't think I can commit to that right now.", 0),
("Let's review the document together tomorrow.", 0),
("I respect your boundaries.", 0),
("Thank you for being so understanding.", 0),
("I'll make sure to get this done by Friday.", 0),
("Are you feeling any better today?", 0),
("I really don't mind either way.", 0),
("Let's focus on the positives here.", 0),
("You're taking my words out of context on purpose.", 1),
("You're the most selfish person I've ever met.", 1),
("I wouldn't have cheated if you paid more attention to me.", 1),
("You're crazy to think I would ever do that.", 1),
("I'm sorry you feel that way, but I didn't do anything wrong.", 1),
("You always ruin my life.", 1),
("You wouldn't survive a day in the real world.", 1),
("I only hide things because you react so badly.", 1),
("You need to get over it already.", 1),
("Why do you always start fights out of nowhere?", 1),
("Tumhare paas 5 minute milenge baat karne ke liye?", 0),
("Mujhe lagta hai hume thoda space chahiye abhi.", 0),
("Tum kahan par ho abhi?", 0),
("Main tumhara wait kar raha hu neeche.", 0),
("Mujhe uspe gussa aa raha tha.", 0),
("Tumne bohot acha perform kiya kal.", 0),
("Sorry for the late reply.", 0),
("Main kal gym nahi ja paunga.", 0),
("Mujhe sach mein kuch nahi pata is baare mein.", 0),
("Hum mil ke is problem ko solve karenge.", 0),
("Tumhe sach aur jhooth ka fark nahi pata.", 1),
("Main apni job chhod dunga agar tum waha gayi toh.", 1),
("Tum har baat ka issue kyu banati ho?", 1),
("Tumhe meri thodi si bhi fikar nahi hai.", 1),
("Meri aadat aisi hi hai, sehna hai toh raho warna jao.", 1),
("Tum dimagi taur par beemar ho gaye ho.", 1),
("Main hi tumhari har farmaish poori karta hu, koi aur nahi karega.", 1),
("Tumne hi mujhe uksaya tha maarne ke liye.", 1),
("Tum doston ke saath hamesha mujhe ignore karte ho.", 1),
("Tum bas rone ka natak karna jante ho.", 1),
("I'll ping you once the report is generated.", 0),
("Can you confirm if you received my email?", 0),
("I'm not in the right headspace to discuss this right now.", 0),
("I appreciate your prompt response.", 0),
("Let's have a quick sync tomorrow morning.", 0),
("I'm happy to help if you're stuck.", 0),
("Could you please lower the volume a bit?", 0),
("I'm really looking forward to the weekend.", 0),
("I completely stand by my team on this.", 0),
("I owe you one for this.", 0),
("You're making up memories that never happened.", 1),
("If you don't trust me, then what's the point of us?", 1),
("You're always trying to play the martyr.", 1),
("I guess I can't do anything right in your eyes.", 1),
("You're just being paranoid again.", 1),
("You'll regret it if you leave me.", 1),
("You made me fail because you kept distracting me.", 1),
("I was just giving you constructive criticism, don't be so fragile.", 1),
("You always manage to make me feel terrible.", 1),
("Nobody else cares about your problems.", 1),
("Darwaza lock kar diya kya tumne?", 0),
("Main tumhe thodi der mein link bhejta hu.", 0),
("Mujhe tumhari aawaz theek se nahi aa rahi.", 0),
("Main tumhare sath hu is situation mein.", 0),
("Aaj maine bahut tasty khana banaya hai.", 0),
("Tum theek se soye nahi ho shayad.", 0),
("Mujhe lagta hai ye idea kaam nahi karega.", 0),
("Main poori koshish karunga kal aane ki.", 0),
("Tumhari smile bahut achi hai.", 0),
("Mujhe akele bahar jana pasand nahi hai zyada.", 0),
("Tumhari toh kismat achi thi jo main mil gaya.", 1),
("Tum deliberately mujhe hurt karne ki koshish karte ho.", 1),
("Agar main gussa karta hu toh pyaar bhi toh karta hu.", 1),
("Tum uske baare mein hamesha hi baat kyu karte ho?", 1),
("Tumhara dimaag kharab hai, jaake ilaj karwao.", 1),
("Main hi bewaqoof hu jo tumhari itni respect karta hu.", 1),
("Tum hamesha apni galti mujh par daalte ho.", 1),
("Maine toh sirf mazak mein kaha tha, tum seedha dil pe le liye.", 1),
("Agar tumne ye kaam nahi kiya, toh main baat nahi karunga.", 1),
("Tumne meri life ka sabse bada headache ban chuke ho.", 1),
("I'm sorry, I cannot attend the meeting today.", 0),
("What time works best for you?", 0),
("I feel a little hurt by what you said earlier.", 0),
("I will definitely look into this issue.", 0),
("Let me know if I need to change anything.", 0),
("I'm glad we cleared that up.", 0),
("Have a good night's sleep.", 0),
("I'm sorry to hear that you're going through this.", 0),
("I'll take the responsibility for this mistake.", 0),
("Let's stick to the original plan.", 0),
("You're literally crazy.", 1),
("You always blow things out of proportion, it's exhausting.", 1),
("You owe me for everything I've bought you.", 1),
("You're the only one who thinks that.", 1),
("I guess I'll just starve then since you didn't cook.", 1),
("You wouldn't act like this if you respected me.", 1),
("You're making a scene for no reason.", 1),
("You never consider my feelings, do you?", 1),
("I'm doing this for your own good, you just don't see it.", 1),
("You deliberately push my buttons.", 1),
("Mujhe ek zaruri kaam aa gaya hai.", 0),
("Tumne medicine li time pe?", 0),
("Main theek hu, bas thak gaya hu travel karke.", 0),
("Aapke paas do minute hain?", 0),
("Main apni galti maanta hu.", 0),
("Hum kal aaram se is topic par discuss karenge.", 0),
("Tumhara present kafi thoughtful tha, thanks.", 0),
("Main bas check kar raha tha ki tum safe pahunch gaye.", 0),
("Please mujhe update dete rehna.", 0),
("Maine ye intentionally nahi kiya tha.", 0),
("Tumhe lagta hai tum bahut mahan ho.", 1),
("Tumhari problem ye hai ki tumne kabhi mehnat nahi ki.", 1),
("Maine aisa bola hi nahi, tum khud soch lete ho kuch bhi.", 1),
("Tum hamesha victim banne ki acting karte ho.", 1),
("Agar tum mere sath nahi ho, toh mere khilaf ho.", 1),
("Tumhara rona bas ek natak hai attention paane ka.", 1),
("Main tumhare liye marne ko tayar hu, aur tum time tak nahi nikal sakte.", 1),
("Tumhari wajeh se meri family suffer kar rahi hai.", 1),
("Tum hamesha baat ka batangad banate ho.", 1),
("Tumhe sab kuch theek se samjhana padta hai, akal naam ki cheez nahi hai.", 1),
("I'm planning to work from home tomorrow.", 0),
("Can you send me the address again?", 0),
("I don't appreciate being spoken to like that.", 0),
("I'm really tired, can we talk tomorrow?", 0),
("I've already paid the electricity bill.", 0),
("I'm so sorry for your loss.", 0),
("I need you to be honest with me.", 0),
("Let's try not to interrupt each other.", 0),
("I think I made a mistake here.", 0),
("I'm just going to relax for the rest of the day.", 0),
("You are overreacting as usual.", 1),
("You're lucky I tolerate your nonsense.", 1),
("Why do you always try to start a fight?", 1),
("If you loved me, you'd know what's wrong without me telling you.", 1),
("You are the one who started this, I'm just finishing it.", 1),
("You're acting just like your toxic friends.", 1),
("You always twist reality to suit your narrative.", 1),
("I wouldn't have to be secretive if you weren't so controlling.", 1),
("You have no right to be upset about this.", 1),
("I'll just stop talking completely since everything I say is wrong.", 1),
("Mujhe kal office ke kaam se bahar jana hai.", 0),
("Tum kya chahte ho hum kahan chalein?", 0),
("Main tumhari situation samajhne ki try kar raha hu.", 0),
("Tumhari nayi shirt bahut achi lag rahi hai.", 0),
("Mujhe thoda headache ho raha hai, baad mein baat karein?", 0),
("Main tumhare bina ye nahi kar pata.", 0),
("Hum is problem ka hal nikalenge, tension mat lo.", 0),
("Maine payment receive kar li hai.", 0),
("Kal ka kya schedule hai tumhara?", 0),
("Main apni boundary cross nahi karna chahta.", 0),
("Tumne hi mujhe pagal kar diya hai.", 1),
("Tumhare dimaag mein hamesha kachra hi bhara rehta hai.", 1),
("Main jaa raha hu, tumhe meri yaad bhi nahi aayegi.", 1),
("Tumhara dukh sabse bada hai, baaki sab toh mazze mein hain haina?", 1),
("Tum mujhe pagal sabit karne par tule ho.", 1),
("Maine kuch galat nahi kiya, ye tumhari khud ki problem hai.", 1),
("Tum doston ke saath hasee mazak kar sakte ho par mere saath nahi.", 1),
("Main hi bewakoof tha jo maine aapse umeed rakhi.", 1),
("Tum hamesha mere intentions par doubt karte ho.", 1),
("Tum apni galtiyo ko manne ki himmat nahi rakhte.", 1),
("I'll have the chicken salad, please.", 0),
("I'm running about 5 minutes late.", 0),
("That doesn't sound right to me.", 0),
("I'd appreciate it if you could give me a heads up next time.", 0),
("I'm really grateful for your help.", 0),
("Can we try to be a bit more organized?", 0),
("I'm sorry if I came across as rude.", 0),
("I feel a bit overwhelmed right now.", 0),
("Let's stick to the facts.", 0),
("I'll handle this part of the project.", 0),
("You never pay attention to what I actually say.", 1),
("You are intentionally trying to confuse me.", 1),
("Nobody in your family even likes you.", 1),
("You owe me for picking you up the other day.", 1),
("I'm the only person you have left.", 1),
("You're exaggerating the whole situation.", 1),
("You made me fail the interview because we argued last night.", 1),
("You always have to be the victim in every story.", 1),
("If you leave, you'll be nothing without me.", 1),
("You should be apologizing to me instead.", 1),
("Subah jaldi uthna hai, so jao ab.", 0),
("Main apne dost ke ghar par hu.", 0),
("Tumne jo bola mujhe thoda bura laga.", 0),
("Main tumhe baad mein message karunga.", 0),
("Tum apna best try karte raho.", 0),
("Mujhe sach mein yaad nahi aa raha hai.", 0),
("Hum weekend pe milenge pakka.", 0),
("Tumhe chinta karne ki zarurat nahi hai.", 0),
("Mujhe thoda ajeeb lag raha tha wahan.", 0),
("Thanks for understanding my situation.", 0),
("Tumhara drama mujhe bilkul pasand nahi.", 1),
("Agar main tumhari wajah se late hua toh soch lena.", 1),
("Tumhara problem ye hai ki tum khud ko perfect samajhti ho.", 1),
("Tumhare maa-baap ne tumhe koi sanskaar nahi diye.", 1),
("Main sab janta hu, mujhse jhooth bolne ki koshish mat karo.", 1),
("Tum hamesha sabke samne meri bezati karte ho.", 1),
("Main toh bas check kar raha tha ki tum sach bolte ho ya nahi.", 1),
("Tum aisi harkate karoge toh main bhi waisa hi behave karunga.", 1),
("Tumhari wajah se meri health kharab ho rahi hai.", 1),
("Tum sabko mere khilaf bhadka rahe ho.", 1),
("Can I call you back in 10 minutes?", 0),
("I'm currently busy with some urgent work.", 0),
("Let's go to that new cafe today.", 0),
("I don't think I can make it to the party.", 0),
("I value our relationship very much.", 0),
("I need to rethink my priorities.", 0),
("I am feeling very tired today.", 0),
("Could you please close the window?", 0),
("I think it's a great opportunity for you.", 0),
("I'll do my best to help you out.", 0),
("You always try to make me feel guilty.", 1),
("You're just projecting your own insecurities onto me.", 1),
("If you don't do this, it proves you don't care.", 1),
("I never agreed to that, you're making things up.", 1),
("You are the reason our relationship is falling apart.", 1),
("You have a terrible memory, that never happened.", 1),
("I'm only controlling because you can't be trusted.", 1),
("You wouldn't be crying if you weren't guilty.", 1),
("You always want everything to be your way.", 1),
("I sacrificed my happiness for you.", 1),
("Mujhe aaj bahut bhookh lag rahi hai.", 0),
("Kya main aapse kal mil sakta hu?", 0),
("Main apna stand clear kar chuka hu.", 0),
("Tumhari presentation kafi achi thi aaj.", 0),
("Mujhe thoda ajeeb feel ho raha tha.", 0),
("Main is project ke liye available nahi hu.", 0),
("Hum ek team ki tarah kaam karenge.", 0),
("Maine aapko email send kar diya hai.", 0),
("Tumhara idea work nahi kiya.", 0),
("Main aage se aur careful rahunga.", 0),
("Tumhara dimag padhna aasan hai mere liye.", 1),
("Main tumhare aasuon par pighalne wala nahi hu.", 1),
("Tum jaan-boojhkar overreact kar rahe ho.", 1),
("Tumhara intention hi galat tha shuru se.", 1),
("Agar tumne phone nahi uthaya toh samajh lena.", 1),
("Meri kisi ko zaroorat hi nahi hai is duniya mein.", 1),
("Tum sab jante hue bhi anjaan banne ki acting karte ho.", 1),
("Main gusse mein wahi bolta hu jo sach hota hai.", 1),
("Tumhe lagta hai main pagal hu?", 1),
("Tum hamesha mujhe provoke karte ho faltu batein bol ke.", 1)
]